### ISSUE TITLE
Invert / Flip display?

### ISSUE THREAD

**Issue by systematicallyrandom** [trip5/EspHome-Led-Clock#3]
I have a situation where I would like to mount the Sinilink clock upside down using it's mounting holes. Is there a way to flip the display? I can change the segment order string to flip the digits, but the order if the digits needs to be reversed as well. Is this possible?

**Comment by trip5** [comment]
Oh!  You inverted the numbers by changing `segment_mapping: PGFEDCBA` to something else!  Would you mind sharing that?  It'll save me a bit of work!  And yeah, it should be fairly easy to manipulate the digits to go 4321 instead of 1234 and with the digits flipped, it should work perfectly...  Let me take a look after a few days.  I've got a trip to go on but I'll get to it when I get back and just make it an option setting in the YAML.

**Comment by systematicallyrandom** [comment]
For sure! Inverted digit segment_mapping is: **PGCBAFED**. (Normal is PGFEDCBA.)

The segments are designated as such:
```
     A
    ---
 F |   | B
    -G-
 E |   | C
    ---
     D
```
The segment mapping tells the code which bits are mapped to which segments in the physical hardware ([reference](https://robojax.com/learn/arduino/robojax-TM1637_display_manual.pdf)). I simply turned it upside down and translated the new mapping sequence to the existing one.

I'm not sure if it will be of any help, but the [TM1537 ESPHome component](https://esphome.io/components/display/tm1637.html) has an `inverted:` option that you could potentially get some code ideas from?

**Comment by trip5** [comment]
It absolutely is a good idea to just add it to the config of the device.  And the inverted code in the official TM1637 looks pretty easy to add so would work seamlessly.  I'll get back to you in a few days!

**Comment by trip5** [comment]
I think I got it.  By the way, we were both thinking about the segment map in the wrong way... that pic is just for the regular TM1650 and how the original font is mapped.  It's more like:
```
//
//      A
//     ---
//  F |   | B
//     -G-
//  E |   | C
//     ---
//      D   P
// Regular TM1650 is PABCDEFG

// For others, you will need to remap as such: 0b12345678,
//      2
//     ---
//  7 |   | 3
//     -8-
//  6 |   | 4
//     ---
//      5   1
```
So upside-down Sinilink XY-Clock is `PDCBGFEA`

Regular TM1650 makes it more easy to see what happens (because that's what this font was designed for: `PABCDEFG -> PDEFABCG)`

In any case, an `invert` option would have made things possibly screwy with other segment mappings so you'll have to continue to use a segment remap as well as a new option `backward: true` in the `Display:` section.

But just grab the new YAML and it'll be fine.  Got some other minor updates in there too.  OTA will show status now.  😄

**Comment by systematicallyrandom** [comment]
I was out, but finally got to try this and it is working great! Thank you so much!
